auth_enabled: false

server:
  http_listen_port: 3102
  grpc_listen_port: 9098

ingester:
  lifecycler:
    address: 192.168.56.182
    ring:
      kvstore:
        store: consul
        consul:
          host: 192.168.56.180:8500
      heartbeat_timeout: 1m
      replication_factor: 1
    num_tokens: 128
    heartbeat_period: 5s
    join_after: 0s
    min_ready_duration: 10s
    interface_names:
      - "eth0"
    final_sleep: 30s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-07-31
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_
        period: 24h

storage_config:
  aws:
    s3: s3://697d0993dd097f38d5b8:9f88738761b57c63f6a81bdfd471@192.168.56.180:9000/loki
    s3forcepathstyle: true

  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    resync_interval: 5s
    shared_store: s3


limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  chunk_cache_config:
    redis:
        endpoint: "192.168.56.180:6379"
        timeout: 100ms
        expiration: 0s
  max_look_back_period: 0s
  write_dedupe_cache_config:
    redis:
      endpoint: "192.168.56.180:6379"
      timeout: 100ms
      expiration: 0s

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 1
    inactive_write_throughput: 1
    provisioned_read_throughput: 5
    provisioned_write_throughput: 5
  index_tables_provisioning:
    inactive_read_throughput: 1
    inactive_write_throughput: 1
    provisioned_read_throughput: 5
    provisioned_write_throughput: 5
  retention_deletes_enabled: false
  retention_period: 0s