version: '3'

services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
