version: '3'

services:
  promtail:
    image: grafana/promtail:2.2.1
    ports:
      - "9080:9080"
    volumes:
      - ./conf:/etc/promtail
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml