version: '3'

services:
  consul:
    image: consul:1.9
    container_name: consul
    ports:
      - "8500:8500"
    command: agent -log-level=info -dev -ui -client 0.0.0.0
    volumes:
      - ./consul/config:/consul/config
      - ./consul/data:/consul/data