version: '3'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    entrypoint: sh
    command: -c 'mkdir -p /export/loki && /usr/bin/minio server --console-address :9001 /export'
    environment:
      - MINIO_ACCESS_KEY=697d0993dd097f38d5b8
      - MINIO_SECRET_KEY=9f88738761b57c63f6a81bdfd471
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3